version: '3.9'

services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    build:
      context: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py loaddata user.json &&
             gunicorn podaj_lapke.wsgi:application --bind 0.0.0.0:8000 --reload"
    ports:
      - 8000:8000
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy